# Generated by Django 4.2.11 on 2024-05-25 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0005_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='room.ChannelParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
