# Generated by Django 4.2.11 on 2024-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_channel_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
